services:
  transform:
    container_name: transform-case-data
    build: .
    env_file: ../.env
    depends_on:
      test-source-data-pre-transform:
        condition: service_completed_successfully
    command: run
    volumes:
      - /Users/emmacorbett/Documents/work-projects/home-office/dbt-proto/transformation:/usr/app/dbt
      - /Users/emmacorbett/Documents/work-projects/home-office/dbt-proto/transformation/profiles:/root/.dbt/
  test-source-data-pre-transform:
    container_name: test-source-data-pre-transform
    env_file: ../.env
    build: .
    command: "test --select source:*"
    volumes:
      - /Users/emmacorbett/Documents/work-projects/home-office/dbt-proto/transformation:/usr/app/dbt
      - /Users/emmacorbett/Documents/work-projects/home-office/dbt-proto/transformation/profiles:/root/.dbt/
  test-transformations:
    container_name: test-transformations
    env_file: ../.env
    build: .
    environment:
      - DBT_TARGET=testing-not-prod
    volumes:
      - /Users/emmacorbett/Documents/work-projects/home-office/dbt-proto/transformation:/usr/app/dbt
      - /Users/emmacorbett/Documents/work-projects/home-office/dbt-proto/transformation/profiles:/root/.dbt/
    entrypoint: bash -c "dbt run --full-refresh && dbt test"

